theme: jekyll-theme-minimal
<style type="text/css">
    body {
    background: url(http://imgsrc.baidu.com/forum/pic/item/6e4e302ac65c10381be07ab4bf119313b17e89cc.jpg) !important;
    background-repeat: no-repeat !important;
    background-position: -10% 100% !important;
    background-attachment: fixed !important;
    background-size: 25% !important;
}
</style>
